name: Deploy to Self-Hosted Server

on:
    push:
        branches: ["main", "dev", "Github-Actions"]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Stop Flask Server
              run: |
                sudo systemctl stop flask-app.service || true

            - name: Build and Deploy
              run: |
                cd ~/Projects/project-copilot-clone-2/webserver
                source .venv/bin/activate
                pip install -r requirements.txt
  
            - name: Start Flask service
              run: |
                sudo systemctl start flask-app.service